// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Mac.LearningApplication
{
	public partial class EditorPrefsController : NSViewController
	{
		public EditorPrefsController (IntPtr handle) : base (handle)
		{
		}

        public static AppDelegate App{
            get => (AppDelegate)NSApplication.SharedApplication.Delegate;
        }

        [Export("Preferences")]
        public AppPreferences Preferences{
            get => App.Preferences;
        }
	}
}
