// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Mac.LearningApplication.Sourcelist;

namespace Mac.LearningApplication
{
	public partial class LeftViewController : NSViewController
	{
        private SubviewType ViewType=SubviewType.None;

        public delegate void ViewTypeChangedDelegate(SubviewType viewType);
        public event ViewTypeChangedDelegate ViewTypeChanged;

        public LeftViewController (IntPtr handle) : base (handle)
		{
		}

        private void DisplaySubView(SubviewType type){
            if (ViewType == type){
                return;
            }
            ViewType = type;
            RaiseViewTypeChanged(type);
        }

        internal void RaiseViewTypeChanged(SubviewType type)
        {
            ViewTypeChanged?.Invoke(type);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }
        public override void ViewDidLayout()
        {
            base.ViewDidLayout();
            SourceList.Initialize();

            var control = new SourceListItem("Control Type");
            control.AddItem("Button", () => {
                DisplaySubView(SubviewType.Buttons);
            });
            control.AddItem("Checkboxes & Radio Buttons",()=>{
                DisplaySubView(SubviewType.CheckAndRadioButtons);
            });
            SourceList.AddItem(control);
            SourceList.ReloadData();
            SourceList.ExpandItem(null, true);
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
            //SourceList.Initialize();

            //var control = new SourceListItem("Control Type");
            //control.AddItem("Control Type");
            //control.AddItem("Button");
            //control.AddItem("Checkboxes & Radio Buttons");
            //SourceList.AddItem(control);
            //SourceList.ReloadData();
            //SourceList.ExpandItem(null,true);
        }
	}
}
