// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Mac.LearningApplication
{
    public enum SubviewType
    {
        None,
        Buttons,
        CheckAndRadioButtons,
        MenuControls,
        SelectionControls,
        IndicatorControls,
        TextControls,
        ContentViews
    }
	public partial class RightViewController : NSViewController
	{
		public RightViewController (IntPtr handle) : base (handle)
		{
		}

        public void ShowView(SubviewType type){
            switch(type){
                case SubviewType.Buttons:
                    PerformSegue("ButtonsSegue", this);
                    break;
                case SubviewType.CheckAndRadioButtons:
                    PerformSegue("CheckboxSegue", this);
                    break;
                case SubviewType.MenuControls:
                    PerformSegue("MenuSegue", this);
                    break;
                case SubviewType.SelectionControls:
                    PerformSegue("SelectionSegue", this);
                    break;
                case SubviewType.IndicatorControls:
                    PerformSegue("IndicatorSegue", this);
                    break;
                case SubviewType.TextControls:
                    PerformSegue("TextSegue", this);
                    break;
                case SubviewType.ContentViews:
                    PerformSegue("ContentSegue", this);
                    break;
            }
        }
	}
}
