// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Mac.LearningApplication
{
	public partial class TextViewController : NSViewController
	{
		public TextViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
